### ISSUE TITLE
Adding Keyframes

### ISSUE THREAD

**Issue by polygonmaster** [jlampel/orient_to_selection#1]
Hi, whem I am using it in Blender 3.0, it triggers autokeyframing --> add keyframes. This mess with other modifiers and brokes them. Sincerely Smilex

**Comment by jlampel** [comment]
Hey, thanks for the report. It's generally not advised to use this on animated objects since it will mess with the rotation data, but at the very least it shouldn't be adding new keyframes. Fixed!
